(********************************************************************
	@name Coq declarations for model
	@date 2019/05/29 14:29:49
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import examples.BDD2TT.BDD.


Definition InputModel : Model BDDMetamodel_EObject BDDMetamodel_ELink :=
	(Build_Model
		(
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject PortEClass (BuildPort "d")) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject PortEClass (BuildPort "c")) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject PortEClass (BuildPort "s")) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject PortEClass (BuildPort "a")) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject TreeEClass (BuildTree )) :: 
		(Build_BDDMetamodel_EObject PortEClass (BuildPort "b")) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment false)) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment false)) :: 
		(Build_BDDMetamodel_EObject BDDEClass (BuildBDD "Test")) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject InputPortEClass (BuildInputPort ((BuildPort "d")) )) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment false)) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment false)) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment false)) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment true)) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment true)) :: 
		(Build_BDDMetamodel_EObject InputPortEClass (BuildInputPort ((BuildPort "c")) )) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment true)) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject AssignmentEClass (BuildAssignment false)) :: 
		(Build_BDDMetamodel_EObject OutputPortEClass (BuildOutputPort ((BuildPort "s")) )) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject LeafEClass (BuildLeaf ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject InputPortEClass (BuildInputPort ((BuildPort "a")) )) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject SubtreeEClass (BuildSubtree ((BuildTree )) )) :: 
		(Build_BDDMetamodel_EObject InputPortEClass (BuildInputPort ((BuildPort "b")) )) :: 
		nil)
		(
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink PortOwnerEReference (BuildPortOwner (BuildPort "d") (BuildBDD "Test"))) ::
		(Build_BDDMetamodel_ELink TreeOwnerBDDEReference (BuildTreeOwnerBDD (BuildTree ) (BuildBDD "Test"))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink PortOwnerEReference (BuildPortOwner (BuildPort "c") (BuildBDD "Test"))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink PortOwnerEReference (BuildPortOwner (BuildPort "s") (BuildBDD "Test"))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink PortOwnerEReference (BuildPortOwner (BuildPort "a") (BuildBDD "Test"))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForOneEReference (BuildTreeOwnerSubtreeForOne (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink TreeOwnerSubtreeForZeroEReference (BuildTreeOwnerSubtreeForZero (BuildTree ) (BuildSubtree ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink PortOwnerEReference (BuildPortOwner (BuildPort "b") (BuildBDD "Test"))) ::

		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment false) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment false) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment false) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment false) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink BDDPortsEReference (BuildBDDPorts (BuildBDD "Test") ((BuildPort "a") :: (BuildPort "b") :: (BuildPort "c") :: (BuildPort "d") :: (BuildPort "s") :: nil ))) ::
		(Build_BDDMetamodel_ELink BDDTreeEReference (BuildBDDTree (BuildBDD "Test") (BuildTree ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment false) :: nil ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment false) :: nil ))) ::
		(Build_BDDMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees (BuildInputPort ((BuildPort "d")) ) ((BuildSubtree ((BuildTree )) ) :: (BuildSubtree ((BuildTree )) ) :: nil ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "a")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment true) :: nil ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment false) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment false) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "d")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment true) :: nil ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment false) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment false) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "b")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment false) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment false) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment true) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment true) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "d")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment true) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment true) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees (BuildInputPort ((BuildPort "c")) ) ((BuildSubtree ((BuildTree )) ) :: (BuildSubtree ((BuildTree )) ) :: (BuildSubtree ((BuildTree )) ) :: nil ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "c")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment true) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment true) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment false) :: nil ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment false) :: nil ))) ::
		(Build_BDDMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort (BuildAssignment false) (BuildOutputPort ((BuildPort "s")) ))) ::
		(Build_BDDMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner (BuildAssignment false) (BuildLeaf ((BuildTree )) ))) ::
		(Build_BDDMetamodel_ELink OutputPortAssignmentsEReference (BuildOutputPortAssignments (BuildOutputPort ((BuildPort "s")) ) ((BuildAssignment false) :: (BuildAssignment false) :: (BuildAssignment true) :: (BuildAssignment false) :: (BuildAssignment false) :: (BuildAssignment true) :: (BuildAssignment false) :: (BuildAssignment false) :: (BuildAssignment true) :: nil ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment false) :: nil ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment true) :: nil ))) ::
		(Build_BDDMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments (BuildLeaf ((BuildTree )) ) ((BuildAssignment false) :: nil ))) ::
		(Build_BDDMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees (BuildInputPort ((BuildPort "a")) ) ((BuildSubtree ((BuildTree )) ) :: nil ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "c")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "b")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreePortEReference (BuildSubtreePort (BuildSubtree ((BuildTree )) ) (BuildInputPort ((BuildPort "c")) ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne (BuildSubtree ((BuildTree )) ) (BuildTree ))) ::
		(Build_BDDMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees (BuildInputPort ((BuildPort "b")) ) ((BuildSubtree ((BuildTree )) ) :: (BuildSubtree ((BuildTree )) ) :: nil ))) ::
		nil)
	).
