(********************************************************************
	@name Coq declarations for model
	@date 2020/12/16 12:00:50
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import examples.TT2BDD.BDDv2.


Definition InputModel : Model bddMetamodel_EObject bddMetamodel_ELink :=
	(Build_Model
		(
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "1471086700_Assignment" false)) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "270095066_Subtree" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1771667101_Leaf" ))) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "929383713_Assignment" false)) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "702061917_Leaf" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "574268151_Subtree" ))) :: 
		(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "1217875525_InputPort" "b"))) :: 
		(Build_bddMetamodel_EObject BDDEClass (BuildBDD "364639279_BDD" "Test")) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "890545344_Assignment" false)) :: 
		(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "1806431167_InputPort" "d"))) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "865667596_Assignment" false)) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1813187653_Subtree" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "48208774_Leaf" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1604002113_Subtree" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1810742349_Leaf" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "38262958_Subtree" ))) :: 
		(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port OutputPortEClass (BuildOutputPort "552936351_OutputPort" "s"))) :: 
		(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "1427040229_InputPort" "a"))) :: 
		(Build_bddMetamodel_EObject PortEClass (Build_Abstract_Port InputPortEClass (BuildInputPort "1353530305_InputPort" "c"))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "363509958_Leaf" ))) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "802243390_Assignment" true)) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "2033968586_Assignment" true)) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "423583818_Assignment" true)) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1832532108_Leaf" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "1306834002_Leaf" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1354083458_Subtree" ))) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "154319946_Assignment" false)) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "1787079037_Subtree" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree SubtreeEClass (BuildSubtree "50699452_Subtree" ))) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "13803304_Leaf" ))) :: 
		(Build_bddMetamodel_EObject AssignmentEClass (BuildAssignment "71706941_Assignment" false)) :: 
		(Build_bddMetamodel_EObject TreeEClass (Build_Abstract_Tree LeafEClass (BuildLeaf "556488341_Leaf" ))) :: 
		nil)
		(
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "1471086700_Assignment" false)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "1471086700_Assignment" false)  (BuildLeaf "1810742349_Leaf" ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "270095066_Subtree" )  (BuildInputPort "1806431167_InputPort" "d"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "270095066_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "48208774_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "270095066_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1306834002_Tree" ) ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1771667101_Leaf" ) ( (BuildAssignment "71706941_Assignment" false) :: nil ))) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "929383713_Assignment" false)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "929383713_Assignment" false)  (BuildLeaf "363509958_Leaf" ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "702061917_Leaf" ) ( (BuildAssignment "802243390_Assignment" true) :: nil ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "574268151_Subtree" )  (BuildInputPort "1353530305_InputPort" "c"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "574268151_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1832532108_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "574268151_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1771667101_Tree" ) ))) ::
		(Build_bddMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "1217875525_InputPort" "b") ( (BuildSubtree "1787079037_Subtree" ) ::  (BuildSubtree "38262958_Subtree" ) :: nil ))) ::
		(Build_bddMetamodel_ELink BDDPortsEReference (BuildBDDPorts  (BuildBDD "364639279_BDD" "Test") ( (Build_Abstract_Port InputPortEClass  (BuildInputPort "1427040229_Port" "a") ) ::  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1217875525_Port" "b") ) ::  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1353530305_Port" "c") ) ::  (Build_Abstract_Port InputPortEClass  (BuildInputPort "1806431167_Port" "d") ) ::  (Build_Abstract_Port OutputPortEClass  (BuildOutputPort "552936351_Port" "s") ) :: nil ))) ::
		(Build_bddMetamodel_ELink BDDTreeEReference (BuildBDDTree  (BuildBDD "364639279_BDD" "Test")  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1604002113_Tree" ) ))) ::
		(Build_bddMetamodel_ELink BDDTreesEReference (BuildBDDTrees  (BuildBDD "364639279_BDD" "Test")  nil )) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "890545344_Assignment" false)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "890545344_Assignment" false)  (BuildLeaf "556488341_Leaf" ))) ::
		(Build_bddMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "1806431167_InputPort" "d") ( (BuildSubtree "50699452_Subtree" ) ::  (BuildSubtree "270095066_Subtree" ) :: nil ))) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "865667596_Assignment" false)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "865667596_Assignment" false)  (BuildLeaf "1306834002_Leaf" ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1813187653_Subtree" )  (BuildInputPort "1353530305_InputPort" "c"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1813187653_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "13803304_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1813187653_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "702061917_Tree" ) ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "48208774_Leaf" ) ( (BuildAssignment "2033968586_Assignment" true) :: nil ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1604002113_Subtree" )  (BuildInputPort "1427040229_InputPort" "a"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1604002113_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "38262958_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1604002113_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "50699452_Tree" ) ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1810742349_Leaf" ) ( (BuildAssignment "1471086700_Assignment" false) :: nil ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "38262958_Subtree" )  (BuildInputPort "1217875525_InputPort" "b"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "38262958_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "363509958_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "38262958_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1354083458_Tree" ) ))) ::
		(Build_bddMetamodel_ELink OutputPortAssignmentsEReference (BuildOutputPortAssignments  (BuildOutputPort "552936351_OutputPort" "s") ( (BuildAssignment "1471086700_Assignment" false) ::  (BuildAssignment "154319946_Assignment" false) ::  (BuildAssignment "802243390_Assignment" true) ::  (BuildAssignment "890545344_Assignment" false) ::  (BuildAssignment "71706941_Assignment" false) ::  (BuildAssignment "2033968586_Assignment" true) ::  (BuildAssignment "929383713_Assignment" false) ::  (BuildAssignment "865667596_Assignment" false) ::  (BuildAssignment "423583818_Assignment" true) :: nil ))) ::
		(Build_bddMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "1427040229_InputPort" "a") ( (BuildSubtree "1604002113_Subtree" ) :: nil ))) ::
		(Build_bddMetamodel_ELink InputPortSubtreesEReference (BuildInputPortSubtrees  (BuildInputPort "1353530305_InputPort" "c") ( (BuildSubtree "574268151_Subtree" ) ::  (BuildSubtree "1354083458_Subtree" ) ::  (BuildSubtree "1813187653_Subtree" ) :: nil ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "363509958_Leaf" ) ( (BuildAssignment "929383713_Assignment" false) :: nil ))) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "802243390_Assignment" true)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "802243390_Assignment" true)  (BuildLeaf "702061917_Leaf" ))) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "2033968586_Assignment" true)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "2033968586_Assignment" true)  (BuildLeaf "48208774_Leaf" ))) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "423583818_Assignment" true)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "423583818_Assignment" true)  (BuildLeaf "1832532108_Leaf" ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1832532108_Leaf" ) ( (BuildAssignment "423583818_Assignment" true) :: nil ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "1306834002_Leaf" ) ( (BuildAssignment "865667596_Assignment" false) :: nil ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1354083458_Subtree" )  (BuildInputPort "1353530305_InputPort" "c"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1354083458_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "270095066_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1354083458_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "556488341_Tree" ) ))) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "154319946_Assignment" false)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "154319946_Assignment" false)  (BuildLeaf "13803304_Leaf" ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "1787079037_Subtree" )  (BuildInputPort "1217875525_InputPort" "b"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "1787079037_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1813187653_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "1787079037_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "574268151_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreePortEReference (BuildSubtreePort  (BuildSubtree "50699452_Subtree" )  (BuildInputPort "1806431167_InputPort" "d"))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForZeroEReference (BuildSubtreeTreeForZero  (BuildSubtree "50699452_Subtree" )  (Build_Abstract_Tree SubtreeEClass  (BuildSubtree "1787079037_Tree" ) ))) ::
		(Build_bddMetamodel_ELink SubtreeTreeForOneEReference (BuildSubtreeTreeForOne  (BuildSubtree "50699452_Subtree" )  (Build_Abstract_Tree LeafEClass  (BuildLeaf "1810742349_Tree" ) ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "13803304_Leaf" ) ( (BuildAssignment "154319946_Assignment" false) :: nil ))) ::
		(Build_bddMetamodel_ELink AssignmentPortEReference (BuildAssignmentPort  (BuildAssignment "71706941_Assignment" false)  (BuildOutputPort "552936351_OutputPort" "s"))) ::
		(Build_bddMetamodel_ELink AssignmentOwnerEReference (BuildAssignmentOwner  (BuildAssignment "71706941_Assignment" false)  (BuildLeaf "1771667101_Leaf" ))) ::
		(Build_bddMetamodel_ELink LeafAssignmentsEReference (BuildLeafAssignments  (BuildLeaf "556488341_Leaf" ) ( (BuildAssignment "890545344_Assignment" false) :: nil ))) ::
		nil)
	).
