(********************************************************************
	@name Coq declarations for model
	@date 2019/06/03 07:57:18
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import examples.TT2BDD.TT.


Definition InputModel : Model TTMetamodel_EObject TTMetamodel_ELink :=
	(Build_Model
		(
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject LocatedElementEClass (BuildLocatedElement "")) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) true)) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) false)) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) true)) :: 
		(Build_TTMetamodel_EObject InputPortEClass (BuildInputPort (BuildPort (BuildLocatedElement "") "") )) :: 
		(Build_TTMetamodel_EObject RowEClass (BuildRow ((BuildLocatedElement "")) )) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) true)) :: 
		(Build_TTMetamodel_EObject TruthTableEClass (BuildTruthTable ((BuildLocatedElement "")) "Test")) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) false)) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) true)) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) false)) :: 
		(Build_TTMetamodel_EObject InputPortEClass (BuildInputPort (BuildPort (BuildLocatedElement "") "") )) :: 
		(Build_TTMetamodel_EObject RowEClass (BuildRow ((BuildLocatedElement "")) )) :: 
		(Build_TTMetamodel_EObject RowEClass (BuildRow ((BuildLocatedElement "")) )) :: 
		(Build_TTMetamodel_EObject CellEClass (BuildCell ((BuildLocatedElement "")) false)) :: 
		(Build_TTMetamodel_EObject OutputPortEClass (BuildOutputPort (BuildPort (BuildLocatedElement "") "") )) :: 
		nil)
		(
		
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) true) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) true) (BuildPort ((BuildLocatedElement "")) "a"))) ::
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) false) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) false) (BuildPort ((BuildLocatedElement "")) "s"))) ::
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) true) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) true) (BuildPort ((BuildLocatedElement "")) "s"))) ::
		(Build_TTMetamodel_ELink RowOwnerEReference (BuildRowOwner (BuildRow ((BuildLocatedElement "")) ) (BuildTruthTable ((BuildLocatedElement "")) "Test"))) ::
		(Build_TTMetamodel_ELink RowCellsEReference (BuildRowCells (BuildRow ((BuildLocatedElement "")) ) ((BuildCell ((BuildLocatedElement "")) false) :: (BuildCell ((BuildLocatedElement "")) true) :: (BuildCell ((BuildLocatedElement "")) true) :: nil ))) ::
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) true) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) true) (BuildPort ((BuildLocatedElement "")) "b"))) ::
		(Build_TTMetamodel_ELink TruthTablePortsEReference (BuildTruthTablePorts (BuildTruthTable ((BuildLocatedElement "")) "Test") ((BuildPort ((BuildLocatedElement "")) "a") :: (BuildPort ((BuildLocatedElement "")) "b") :: (BuildPort ((BuildLocatedElement "")) "s") :: nil ))) ::
		(Build_TTMetamodel_ELink TruthTableRowsEReference (BuildTruthTableRows (BuildTruthTable ((BuildLocatedElement "")) "Test") ((BuildRow ((BuildLocatedElement "")) ) :: (BuildRow ((BuildLocatedElement "")) ) :: (BuildRow ((BuildLocatedElement "")) ) :: nil ))) ::
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) false) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) false) (BuildPort ((BuildLocatedElement "")) "a"))) ::
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) true) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) true) (BuildPort ((BuildLocatedElement "")) "s"))) ::
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) false) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) false) (BuildPort ((BuildLocatedElement "")) "a"))) ::
		(Build_TTMetamodel_ELink RowOwnerEReference (BuildRowOwner (BuildRow ((BuildLocatedElement "")) ) (BuildTruthTable ((BuildLocatedElement "")) "Test"))) ::
		(Build_TTMetamodel_ELink RowCellsEReference (BuildRowCells (BuildRow ((BuildLocatedElement "")) ) ((BuildCell ((BuildLocatedElement "")) true) :: (BuildCell ((BuildLocatedElement "")) true) :: nil ))) ::
		(Build_TTMetamodel_ELink RowOwnerEReference (BuildRowOwner (BuildRow ((BuildLocatedElement "")) ) (BuildTruthTable ((BuildLocatedElement "")) "Test"))) ::
		(Build_TTMetamodel_ELink RowCellsEReference (BuildRowCells (BuildRow ((BuildLocatedElement "")) ) ((BuildCell ((BuildLocatedElement "")) false) :: (BuildCell ((BuildLocatedElement "")) false) :: (BuildCell ((BuildLocatedElement "")) false) :: nil ))) ::
		(Build_TTMetamodel_ELink CellOwnerEReference (BuildCellOwner (BuildCell ((BuildLocatedElement "")) false) (BuildRow ((BuildLocatedElement "")) ))) ::
		(Build_TTMetamodel_ELink CellPortEReference (BuildCellPort (BuildCell ((BuildLocatedElement "")) false) (BuildPort ((BuildLocatedElement "")) "b"))) ::
				nil)
	).
