(********************************************************************
	@name Coq declarations for model
	@date 2018/08/17 11:47:36
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import examples.HSM2FSM.HSM.


Definition InputModel : Model HSMMetamodel_EObject HSMMetamodel_ELink :=
	(Build_Model
		(
		(Build_HSMMetamodel_EObject AbstractStateEClass (BuildAbstractState "C" "3")) :: 
		(Build_HSMMetamodel_EObject AbstractStateEClass (BuildAbstractState "D" "4")) :: 
		(Build_HSMMetamodel_EObject AbstractStateEClass (BuildAbstractState "E" "5")) :: 
		(Build_HSMMetamodel_EObject AbstractStateEClass (BuildAbstractState "A" "1")) :: 
		(Build_HSMMetamodel_EObject AbstractStateEClass (BuildAbstractState "B" "2")) :: 
		(Build_HSMMetamodel_EObject StateMachineEClass (BuildStateMachine "SM1" "1")) :: 
		(Build_HSMMetamodel_EObject RegularStateEClass (BuildRegularState ((BuildAbstractState "C" "3")) "103")) :: 
		(Build_HSMMetamodel_EObject CompositeStateEClass (BuildCompositeState ((BuildAbstractState "D" "4")) "104")) :: 
		(Build_HSMMetamodel_EObject TransitionEClass (BuildTransition "t1" "1")) :: 
		(Build_HSMMetamodel_EObject TransitionEClass (BuildTransition "t2" "2")) :: 
		(Build_HSMMetamodel_EObject RegularStateEClass (BuildRegularState ((BuildAbstractState "E" "5")) "105")) :: 
		(Build_HSMMetamodel_EObject InitialStateEClass (BuildInitialState ((BuildAbstractState "A" "1")) "101")) :: 
		(Build_HSMMetamodel_EObject InitialStateEClass (BuildInitialState ((BuildAbstractState "B" "2")) "102")) :: 
		(Build_HSMMetamodel_EObject TransitionEClass (BuildTransition "t3" "3")) :: 
		nil)
		(
		(Build_HSMMetamodel_ELink AbstractStateStateMachineEReference (BuildAbstractStateStateMachine (BuildAbstractState "C" "3") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink AbstractStateCompositeStateEReference (BuildAbstractStateCompositeState (BuildAbstractState "C" "3") (BuildCompositeState ((BuildAbstractState "D" "4")) "104"))) ::
		(Build_HSMMetamodel_ELink AbstractStateStateMachineEReference (BuildAbstractStateStateMachine (BuildAbstractState "D" "4") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink AbstractStateStateMachineEReference (BuildAbstractStateStateMachine (BuildAbstractState "E" "5") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink AbstractStateStateMachineEReference (BuildAbstractStateStateMachine (BuildAbstractState "A" "1") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink AbstractStateStateMachineEReference (BuildAbstractStateStateMachine (BuildAbstractState "B" "2") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink AbstractStateCompositeStateEReference (BuildAbstractStateCompositeState (BuildAbstractState "B" "2") (BuildCompositeState ((BuildAbstractState "D" "4")) "104"))) ::
 
		(Build_HSMMetamodel_ELink StateMachineTransitionsEReference (BuildStateMachineTransitions (BuildStateMachine "SM1" "1") ((BuildTransition "t1" "1") :: (BuildTransition "t2" "2") :: (BuildTransition "t3" "3") :: nil ))) ::
		(Build_HSMMetamodel_ELink StateMachineStatesEReference (BuildStateMachineStates (BuildStateMachine "SM1" "1") ((BuildAbstractState "A" "1") :: (BuildAbstractState "B" "2") :: (BuildAbstractState "D" "4") :: (BuildAbstractState "C" "3") :: (BuildAbstractState "E" "5") :: nil ))) ::
		(Build_HSMMetamodel_ELink CompositeStateStatesEReference (BuildCompositeStateStates (BuildCompositeState ((BuildAbstractState "D" "4")) "104") ((BuildAbstractState "B" "2") :: (BuildAbstractState "C" "3") :: nil ))) ::
		(Build_HSMMetamodel_ELink TransitionStateMachineEReference (BuildTransitionStateMachine (BuildTransition "t1" "1") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink TransitionSourceEReference (BuildTransitionSource (BuildTransition "t1" "1") (BuildAbstractState "A" "1"))) ::
		(Build_HSMMetamodel_ELink TransitionTargetEReference (BuildTransitionTarget (BuildTransition "t1" "1") (BuildAbstractState "D" "4"))) ::
		(Build_HSMMetamodel_ELink TransitionStateMachineEReference (BuildTransitionStateMachine (BuildTransition "t2" "2") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink TransitionSourceEReference (BuildTransitionSource (BuildTransition "t2" "2") (BuildAbstractState "B" "2"))) ::
		(Build_HSMMetamodel_ELink TransitionTargetEReference (BuildTransitionTarget (BuildTransition "t2" "2") (BuildAbstractState "C" "3"))) ::
		(Build_HSMMetamodel_ELink TransitionStateMachineEReference (BuildTransitionStateMachine (BuildTransition "t3" "3") (BuildStateMachine "SM1" "1"))) ::
		(Build_HSMMetamodel_ELink TransitionSourceEReference (BuildTransitionSource (BuildTransition "t3" "3") (BuildAbstractState "D" "4"))) ::
		(Build_HSMMetamodel_ELink TransitionTargetEReference (BuildTransitionTarget (BuildTransition "t3" "3") (BuildAbstractState "E" "5"))) ::
		nil)
	).
