(********************************************************************
	@name Coq declarations for model
	@date 2021/10/17 11:25:19
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.DBLP.DBLP.


Definition InputModel : Model DBLPMetamodel_Object DBLPMetamodel_Link :=
	(Build_Model
		(
		(Build_DBLPMetamodel_Object JournalClass (BuildJournal  "Transactions on Software Engineering")) :: 
		(Build_DBLPMetamodel_Object ArticleClass (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2000)) :: 
		(Build_DBLPMetamodel_Object AuthorClass (BuildAuthor  "Manuel")) :: 
		(Build_DBLPMetamodel_Object ArticleClass (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2010)) :: 
		(Build_DBLPMetamodel_Object ArticleClass (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2009)) :: 
		(Build_DBLPMetamodel_Object ArticleClass (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2013)) :: 
		(Build_DBLPMetamodel_Object InProceedingsClass (BuildInProceedings (BuildRecord  "" "" "" "") "inproc1" "ICMT 2005" 2005 0 0 "")) :: 
		(Build_DBLPMetamodel_Object InProceedingsClass (BuildInProceedings (BuildRecord  "" "" "" "") "inproc2" "ICMT 2013" 2013 0 0 "")) :: 
		(Build_DBLPMetamodel_Object AuthorClass (BuildAuthor  "Javi")) :: 
		(Build_DBLPMetamodel_Object AuthorClass (BuildAuthor  "Antonio")) :: 
		(Build_DBLPMetamodel_Object InProceedingsClass (BuildInProceedings (BuildRecord  "" "" "" "") "inproc3" "ICMT 2000" 2000 0 0 "")) :: 
		(Build_DBLPMetamodel_Object JournalClass (BuildJournal  "Information & Software Technology")) :: 
		(Build_DBLPMetamodel_Object AuthorClass (BuildAuthor  "Loli")) :: 
		(Build_DBLPMetamodel_Object InProceedingsClass (BuildInProceedings (BuildRecord  "" "" "" "") "inproc5" "TOOLS" 2006 0 0 "")) :: 
		(Build_DBLPMetamodel_Object InProceedingsClass (BuildInProceedings (BuildRecord  "" "" "" "") "inproc4" "MODELS" 2013 0 0 "")) :: 
		(Build_DBLPMetamodel_Object ArticleClass (BuildArticle (BuildRecord  "" "" "" "") "art1" 0 0 0 "" "" 2006)) :: 
		(Build_DBLPMetamodel_Object JournalClass (BuildJournal  "Computer Standards & Interfaces")) :: 
		(Build_DBLPMetamodel_Object AuthorClass (BuildAuthor  "Martin")) :: 
		(Build_DBLPMetamodel_Object InProceedingsClass (BuildInProceedings (BuildRecord  "" "" "" "") "inproc2" "ICSE" 2014 0 0 "")) :: 
		(Build_DBLPMetamodel_Object ArticleClass (BuildArticle (BuildRecord  "" "" "" "") "art2" 0 0 0 "" "" 2014)) :: 
		nil)
		(
		(Build_DBLPMetamodel_Link JournalArticlesReference (BuildJournalArticles (BuildJournal  "Transactions on Software Engineering") ((BuildArticle (BuildRecord  "" "" "" "") "art2" 0 0 0 "" "" 2014) :: nil ))) ::
		(Build_DBLPMetamodel_Link ArticleJournalReference (BuildArticleJournal (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2000) (BuildJournal  "Information & Software Technology"))) ::
		(Build_DBLPMetamodel_Link AuthorRecordsReference (BuildAuthorRecords (BuildAuthor  "Manuel") ((BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: nil ))) ::
		(Build_DBLPMetamodel_Link ArticleJournalReference (BuildArticleJournal (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2010) (BuildJournal  "Computer Standards & Interfaces"))) ::
		(Build_DBLPMetamodel_Link ArticleJournalReference (BuildArticleJournal (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2009) (BuildJournal  "Information & Software Technology"))) ::
		(Build_DBLPMetamodel_Link ArticleJournalReference (BuildArticleJournal (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2013) (BuildJournal  "Computer Standards & Interfaces"))) ::
		(Build_DBLPMetamodel_Link InProceedingsEditorsReference (BuildInProceedingsEditors (BuildInProceedings (BuildRecord  "" "" "" "") "inproc1" "ICMT 2005" 2005 0 0 "")  nil )) ::
		(Build_DBLPMetamodel_Link InProceedingsEditorsReference (BuildInProceedingsEditors (BuildInProceedings (BuildRecord  "" "" "" "") "inproc2" "ICMT 2013" 2013 0 0 "")  nil )) ::
		(Build_DBLPMetamodel_Link AuthorRecordsReference (BuildAuthorRecords (BuildAuthor  "Javi") ((BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: nil ))) ::
		(Build_DBLPMetamodel_Link AuthorRecordsReference (BuildAuthorRecords (BuildAuthor  "Antonio") ((BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: nil ))) ::
		(Build_DBLPMetamodel_Link InProceedingsEditorsReference (BuildInProceedingsEditors (BuildInProceedings (BuildRecord  "" "" "" "") "inproc3" "ICMT 2000" 2000 0 0 "")  nil )) ::
		(Build_DBLPMetamodel_Link JournalArticlesReference (BuildJournalArticles (BuildJournal  "Information & Software Technology") ((BuildArticle (BuildRecord  "" "" "" "") "art1" 0 0 0 "" "" 2006) :: (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2000) :: (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2009) :: nil ))) ::
		(Build_DBLPMetamodel_Link AuthorRecordsReference (BuildAuthorRecords (BuildAuthor  "Loli") ((BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: nil ))) ::
		(Build_DBLPMetamodel_Link InProceedingsEditorsReference (BuildInProceedingsEditors (BuildInProceedings (BuildRecord  "" "" "" "") "inproc5" "TOOLS" 2006 0 0 "")  nil )) ::
		(Build_DBLPMetamodel_Link InProceedingsEditorsReference (BuildInProceedingsEditors (BuildInProceedings (BuildRecord  "" "" "" "") "inproc4" "MODELS" 2013 0 0 "")  nil )) ::
		(Build_DBLPMetamodel_Link ArticleJournalReference (BuildArticleJournal (BuildArticle (BuildRecord  "" "" "" "") "art1" 0 0 0 "" "" 2006) (BuildJournal  "Information & Software Technology"))) ::
		(Build_DBLPMetamodel_Link JournalArticlesReference (BuildJournalArticles (BuildJournal  "Computer Standards & Interfaces") ((BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2010) :: (BuildArticle (BuildRecord  "" "" "" "") "" 0 0 0 "" "" 2013) :: nil ))) ::
		(Build_DBLPMetamodel_Link AuthorRecordsReference (BuildAuthorRecords (BuildAuthor  "Martin") ((BuildRecord  "" "" "" "") :: (BuildRecord  "" "" "" "") :: nil ))) ::
		(Build_DBLPMetamodel_Link InProceedingsEditorsReference (BuildInProceedingsEditors (BuildInProceedings (BuildRecord  "" "" "" "") "inproc2" "ICSE" 2014 0 0 "")  nil )) ::
		(Build_DBLPMetamodel_Link ArticleJournalReference (BuildArticleJournal (BuildArticle (BuildRecord  "" "" "" "") "art2" 0 0 0 "" "" 2014) (BuildJournal  "Transactions on Software Engineering"))) ::
		nil)
	).
