<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FSM" nsURI="http://FSM/1.0" nsPrefix="FSM">
  <eClassifiers xsi:type="ecore:EClass" name="FStateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//FTransition" containment="true" eOpposite="#//FTransition/stateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//FAbstractState" containment="true" eOpposite="#//FAbstractState/stateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//FStateMachine"
        eOpposite="#//FStateMachine/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FAbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//FAbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FAbstractState" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//FStateMachine"
        eOpposite="#//FStateMachine/states"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FInitialState" eSuperTypes="#//FAbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="FRegularState" eSuperTypes="#//FAbstractState"/>
</ecore:EPackage>
