(********************************************************************
	@name Coq declarations for model
	@date 2021/11/22 10:09:58
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Families2Persons.Families.
Open Scope string_scope.


Definition InputModel : Model FamiliesMetamodel_Object FamiliesMetamodel_Link :=
	(Build_Model
		(
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "David")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Kelly")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Peter")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Jim")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Dylan")) :: 
		(Build_FamiliesMetamodel_Object FamilyClass (BuildFamily  "March")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Brenda")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Cindy")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Jackie")) :: 
		(Build_FamiliesMetamodel_Object MemberClass (BuildMember  "Brandon")) :: 
		(Build_FamiliesMetamodel_Object FamilyClass (BuildFamily  "Sailor")) :: 
		nil)
		(
		(Build_FamiliesMetamodel_Link MemberFamilySonReference (BuildMemberFamilySon (BuildMember  "David") (BuildFamily  "Sailor"))) ::
		(Build_FamiliesMetamodel_Link MemberFamilyDaughterReference (BuildMemberFamilyDaughter (BuildMember  "Kelly") (BuildFamily  "Sailor"))) ::
		(Build_FamiliesMetamodel_Link MemberFamilyFatherReference (BuildMemberFamilyFather (BuildMember  "Peter") (BuildFamily  "Sailor"))) ::
		(Build_FamiliesMetamodel_Link MemberFamilyFatherReference (BuildMemberFamilyFather (BuildMember  "Jim") (BuildFamily  "March"))) ::
		(Build_FamiliesMetamodel_Link MemberFamilySonReference (BuildMemberFamilySon (BuildMember  "Dylan") (BuildFamily  "Sailor"))) ::
		(Build_FamiliesMetamodel_Link FamilyFfatherReference (BuildFamilyFfather (BuildFamily  "March") (BuildMember  "Jim"))) ::
		(Build_FamiliesMetamodel_Link FamilyFmotherReference (BuildFamilyFmother (BuildFamily  "March") (BuildMember  "Cindy"))) ::
		(Build_FamiliesMetamodel_Link FamilyFsonsReference (BuildFamilyFsons (BuildFamily  "March") ((BuildMember  "Brandon") :: nil ))) ::
		(Build_FamiliesMetamodel_Link FamilyFdaughtersReference (BuildFamilyFdaughters (BuildFamily  "March") ((BuildMember  "Brenda") :: nil ))) ::
		(Build_FamiliesMetamodel_Link MemberFamilyDaughterReference (BuildMemberFamilyDaughter (BuildMember  "Brenda") (BuildFamily  "March"))) ::
		(Build_FamiliesMetamodel_Link MemberFamilyMotherReference (BuildMemberFamilyMother (BuildMember  "Cindy") (BuildFamily  "March"))) ::
		(Build_FamiliesMetamodel_Link MemberFamilyMotherReference (BuildMemberFamilyMother (BuildMember  "Jackie") (BuildFamily  "Sailor"))) ::
		(Build_FamiliesMetamodel_Link MemberFamilySonReference (BuildMemberFamilySon (BuildMember  "Brandon") (BuildFamily  "March"))) ::
		(Build_FamiliesMetamodel_Link FamilyFfatherReference (BuildFamilyFfather (BuildFamily  "Sailor") (BuildMember  "Peter"))) ::
		(Build_FamiliesMetamodel_Link FamilyFmotherReference (BuildFamilyFmother (BuildFamily  "Sailor") (BuildMember  "Jackie"))) ::
		(Build_FamiliesMetamodel_Link FamilyFsonsReference (BuildFamilyFsons (BuildFamily  "Sailor") ((BuildMember  "David") :: (BuildMember  "Dylan") :: nil ))) ::
		(Build_FamiliesMetamodel_Link FamilyFdaughtersReference (BuildFamilyFdaughters (BuildFamily  "Sailor") ((BuildMember  "Kelly") :: nil ))) ::
		nil)
	).
